/* Generated By:JavaCC: Do not edit this line. EDLParserConstants.java */
/*
 * Copyright 2003-2007, Regents of the University of Nebraska
 *
 *  Licensed under the University of Nebraska Open Academic License,
 *  Version 1.0 (the "License"); you may not use this file except in
 *  compliance with the License. The License must be provided with
 *  the distribution of this software; if the license is absent from
 *  the distribution, please report immediately to galileo@cse.unl.edu
 *  and indicate where you obtained this software.
 *
 *  You may also obtain a copy of the License at:
 *
 *      http://sofya.unl.edu/LICENSE-1.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package sofya.ed.semantic;

public interface EDLParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int SINGLE_LINE_COMMENT = 2;
  int IMPORT = 3;
  int BEGIN = 4;
  int END = 5;
  int EDLSUITE = 6;
  int OBSERVABLES = 7;
  int PREAMBLE = 8;
  int SYSTEM_CLASSES = 9;
  int MODULE_CLASSES = 10;
  int DATABASE_TAG = 11;
  int TYPE_NAME = 12;
  int INTERCEPTOR = 13;
  int IN = 14;
  int NOT = 15;
  int NEW_OBJECT = 16;
  int CONSTRUCT_OBJECT = 17;
  int CONSTRUCT_FINISH = 18;
  int GET_STATIC = 19;
  int PUT_STATIC = 20;
  int GET_FIELD = 21;
  int PUT_FIELD = 22;
  int CONSTRUCTOR_CALL = 23;
  int STATIC_CALL = 24;
  int VIRTUAL_CALL = 25;
  int INTERFACE_CALL = 26;
  int VIRTUAL_METHOD_ENTER = 27;
  int VIRTUAL_METHOD_EXIT = 28;
  int STATIC_METHOD_ENTER = 29;
  int STATIC_METHOD_EXIT = 30;
  int MONITOR_CONTEND = 31;
  int MONITOR_ACQUIRE = 32;
  int MONITOR_PRE_RELEASE = 33;
  int MONITOR_RELEASE = 34;
  int THROW = 35;
  int CATCH = 36;
  int STATIC_INIT_ENTER = 37;
  int ARRAY_ELEM_LOAD_BOUNDS = 38;
  int ARRAY_ELEM_STORE_BOUNDS = 39;
  int ARRAY_ELEM_LOAD = 40;
  int ARRAY_ELEM_STORE = 41;
  int TRUE = 42;
  int FALSE = 43;
  int VOID = 44;
  int BYTE = 45;
  int CHAR = 46;
  int DOUBLE = 47;
  int FLOAT = 48;
  int INT = 49;
  int LONG = 50;
  int BOOLEAN = 51;
  int SHORT = 52;
  int STRING = 53;
  int JNI_VOID = 54;
  int JNI_BYTE = 55;
  int JNI_CHAR = 56;
  int JNI_DOUBLE = 57;
  int JNI_FLOAT = 58;
  int JNI_INT = 59;
  int JNI_LONG = 60;
  int JNI_BOOLEAN = 61;
  int JNI_SHORT = 62;
  int JNI_ARRAY = 63;
  int WILD_STRING = 64;
  int STRING_LITERAL = 65;
  int UINT = 66;
  int JAVA_ID = 67;
  int LETTER = 68;
  int PART_LETTER = 69;

  int PERM_WILD_STRING = 0;
  int DEFAULT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"@import\"",
    "\"begin\"",
    "\"end\"",
    "\"EDLSuite\"",
    "\"Observables\"",
    "\"Preamble\"",
    "\"System-classes:\"",
    "\"Module-classes:\"",
    "\"Database-tag:\"",
    "\"Type-name:\"",
    "\"#INT\"",
    "\"in\"",
    "\"not\"",
    "\"new_object\"",
    "\"construct_object\"",
    "\"construct_finish\"",
    "\"get_static\"",
    "\"put_static\"",
    "\"get_field\"",
    "\"put_field\"",
    "\"constructor_call\"",
    "\"static_call\"",
    "\"virtual_call\"",
    "\"interface_call\"",
    "\"virtual_method_enter\"",
    "\"virtual_method_exit\"",
    "\"static_method_enter\"",
    "\"static_method_exit\"",
    "\"monitor_contend\"",
    "\"monitor_acquire\"",
    "\"monitor_pre_release\"",
    "\"monitor_release\"",
    "\"throw\"",
    "\"catch\"",
    "\"static_init_enter\"",
    "\"array_element_load_bounds\"",
    "\"array_element_store_bounds\"",
    "\"array_element_load\"",
    "\"array_element_store\"",
    "\"true\"",
    "\"false\"",
    "\"void\"",
    "\"byte\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"boolean\"",
    "\"short\"",
    "\"string\"",
    "\"V\"",
    "\"B\"",
    "\"C\"",
    "\"D\"",
    "\"F\"",
    "\"I\"",
    "\"J\"",
    "\"Z\"",
    "\"S\"",
    "\"[\"",
    "<WILD_STRING>",
    "<STRING_LITERAL>",
    "<UINT>",
    "<JAVA_ID>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"*\"",
    "\"min:\"",
    "\"max:\"",
    "\"No-module:\"",
    "\"+\"",
    "\"-\"",
    "\".*\"",
    "\"+s\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"/\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\".\"",
  };

}
